"""simulator sandboxes

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 16:52:53.430397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(length=40), nullable=False),
    sa.Column('scenario', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('score_paise', sa.Integer(), nullable=False),
    sa.Column('recovered_paise', sa.Integer(), nullable=False),
    sa.Column('incentive_paise', sa.Integer(), nullable=False),
    sa.Column('approvals', sa.Integer(), nullable=False),
    sa.Column('rejections', sa.Integer(), nullable=False),
    sa.Column('blocked', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leaderboard_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leaderboard_entries_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaderboard_entries_scenario'), ['scenario'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaderboard_entries_season'), ['season'], unique=False)

    op.create_table('tick_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('captured_paise', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('failed_paise', sa.Integer(), nullable=False),
    sa.Column('failed_by_method', sa.JSON(), nullable=False),
    sa.Column('link_recovered_paise', sa.Integer(), nullable=False),
    sa.Column('organic_recovered_paise', sa.Integer(), nullable=False),
    sa.Column('baseline_recovered_paise', sa.Integer(), nullable=False),
    sa.Column('lost_paise', sa.Integer(), nullable=False),
    sa.Column('incentive_spent_paise', sa.Integer(), nullable=False),
    sa.Column('wallet_available_paise', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'tick', name='uq_tick_stat_merchant_tick')
    )
    with op.batch_alter_table('tick_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tick_stats_merchant_id'), ['merchant_id'], unique=False)

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_tick', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('auto_proposed', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sim_tick', sa.Integer(), nullable=True))

    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('nickname', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('scenario', sa.String(), server_default='classic', nullable=False))
        batch_op.add_column(sa.Column('season', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('seed', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('sim_start', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('current_tick', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('run_ticks', sa.Integer(), server_default='168', nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), server_default='RUNNING', nullable=False))
        batch_op.add_column(sa.Column('auto_propose', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('wallet_start_paise', sa.Integer(), server_default='2000000', nullable=False))
        batch_op.add_column(sa.Column('leaderboard_entry_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_merchants_token_hash'), ['token_hash'], unique=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_tick', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('organic_tick', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resolved_tick', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_failed_tick'), ['failed_tick'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_organic_tick'), ['organic_tick'], unique=False)

    with op.batch_alter_table('recovery_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_tick', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expires_tick', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('converts_at_tick', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_recovery_links_converts_at_tick'), ['converts_at_tick'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_links_expires_tick'), ['expires_tick'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_links_expires_tick'))
        batch_op.drop_index(batch_op.f('ix_recovery_links_converts_at_tick'))
        batch_op.drop_column('converts_at_tick')
        batch_op.drop_column('expires_tick')
        batch_op.drop_column('created_tick')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_organic_tick'))
        batch_op.drop_index(batch_op.f('ix_payments_failed_tick'))
        batch_op.drop_column('resolved_tick')
        batch_op.drop_column('organic_tick')
        batch_op.drop_column('failed_tick')

    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchants_token_hash'))
        batch_op.drop_column('last_active_at')
        batch_op.drop_column('leaderboard_entry_id')
        batch_op.drop_column('wallet_start_paise')
        batch_op.drop_column('auto_propose')
        batch_op.drop_column('status')
        batch_op.drop_column('run_ticks')
        batch_op.drop_column('current_tick')
        batch_op.drop_column('sim_start')
        batch_op.drop_column('seed')
        batch_op.drop_column('season')
        batch_op.drop_column('scenario')
        batch_op.drop_column('nickname')
        batch_op.drop_column('token_hash')

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_column('sim_tick')

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_column('auto_proposed')
        batch_op.drop_column('created_tick')

    with op.batch_alter_table('tick_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tick_stats_merchant_id'))

    op.drop_table('tick_stats')
    with op.batch_alter_table('leaderboard_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaderboard_entries_season'))
        batch_op.drop_index(batch_op.f('ix_leaderboard_entries_scenario'))
        batch_op.drop_index(batch_op.f('ix_leaderboard_entries_merchant_id'))

    op.drop_table('leaderboard_entries')
    # ### end Alembic commands ###
